language: php
php:
  #- 5.6
  #- 7
  - 7.1
  - 7.2
  - master

matrix:
  fast_finish: true
  allow_failures:
    - php: master

addons:
  mariadb: '10.0'

sudo: required

install:
  # cloning egroupware into egroupware directory
  - git clone --depth=50 --branch=17.1 https://github.com/EGroupware/ADOdb.git egroupware/api/src/Db/ADOdb
  - git clone --depth=50 --branch=17.1 https://github.com/EGroupware/egroupware.git
  # ranking app still needs old compatibility api (phpgwapi+etemplate)
  - git clone --depth=50 --branch=17.1 https://github.com/EGroupware/phpgwapi.git egroupware/phpgwapi
  - git clone --depth=50 --branch=17.1 https://github.com/EGroupware/etemplate.git egroupware/etemplate
  # finally clone own repo, maybe just copy ...
  - git clone --depth=50 --branch=master https://github.com/ralfbecker/ranking.git egroupware/ranking

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpcre3-dev
  - case $(phpenv version-name) in
    "5.6")
       yes "" | pecl install apcu-4.0.11;
       phpenv config-rm xdebug.ini;
       composer require 'phpunit/phpunit:~5.7';
       ;;
    "7"|"7.0"|"7.1"|"7.2"|"7.3"|"master")
       yes "" | pecl install apcu;
       phpenv config-rm xdebug.ini;
       composer require 'phpunit/phpunit:~6.3';
      ;;
    esac
  #- php -m
  - php -i
  - cd egroupware/
  - composer install
  # create data directory
  - sudo mkdir /var/lib/egroupware
  - sudo chown travis /var/lib/egroupware
  - ln -s /var/lib/egroupware/header.inc.php
  # install egroupware using MariaDB as domain "default"
  # and add an admin user "demo" with password "guest"
  - php doc/rpm-build/post_install.php --domain default
    --source_dir `pwd` --start_db '' --autostart_db '' --start_webserver '' --webserver_user ''
    --admin_user demo --admin_passwd guest --admin_email noreply@example.com

script:
  - find ranking -name "*.php" | xargs -n1 php -l | grep -v "^No syntax errors detected in"
  - php doc/rpm-build/post_install.php --install-update-app ranking
  - for test in ranking/tests/*.php; do ./$test; done

cache:
  directories:
    - $HOME/.composer/cache
